import type { Project } from "../interfaces";

export const projects: Project[] = [
  {
    id: "1",
    title: "Web Automation Services Application",
    description:
      "Automation of creation, management and tracking of company orders.",
    technologies: [
      "Python (OOP)",
      "Flask",
      "Next.js 13",
      "Typescript",
      "AWS",
      "MySQL",
    ],
    extendedDescription:
      "Development of a Fullstack application that automates the ordering process of the company. The backend was built in Python using object-oriented programming (OOP) and managed through a REST API developed in Flask. The frontend was developed with functional programming in Next.js 13 with Typescript. The relational databases were developed and modeled in MySQL.",
    startDate: "2021",
    endDate: "2022",
    githubLink: [],
    companyName: "PRODUGAN S.A.S.",
    country: "Colombia",
  },
  {
    id: "2",
    title: "Automated PDF Batches for Psychosocial Surveys",
    description:
      "Automation of loading and analysis of PDF batches with psychosocial surveys.",
    technologies: [
      "Python",
      "Pandas & Numpy",
      "AWS Textract OCR",
      "React",
      "Typescript",
      "MySQL",
      "AWS S3",
    ],
    extendedDescription:
      "Development of a Fullstack project that automates the loading of PDF batches with psychosocial surveys. Use of AWS Textract OCR to transform PDF tables into DataFrames with Pandas and Numpy to assign risk weights. The results were stored in a MySQL database and the CSV files generated by Textract were saved in AWS S3. The frontend was implemented with React and Typescript.",
    startDate: "2023",
    endDate: "2023",
    githubLink: [],
    companyName: "Vita Consulting Salud Y Seguridad En El Trabajo S.A.S.",
    country: "Colombia",
  },
];
